#!/bin/env bash
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$HMOS_NDK/build/cmake/ohos.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DOHOS_STL=c++_static    \
-DOHOS_ARCH=arm64-v8a  \
-DCMAKE_SYSTEM_NAME=OHOS \
-DMNN_USE_LOGCAT=false \
-DMNN_BUILD_BENCHMARK=OFF \
-DMNN_USE_SSE=OFF \
-DMNN_ARM82=ON \
-DMNN_LOW_MEMORY=ON  \
-DMNN_SUPPORT_BF16=ON \
-DMNN_BUILD_TEST=OFF \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

#-DMNN_NPU=ON \

make -j4
